version: '4.8.1'
services:
  db:
    image: mysql
    volumes:
      - ./server:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: project
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
    ports:
      - "9906:3306"
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - 80:8000
    volumes:
      - ./server:/mnt/debug:ro