version: '4.8.1'
services:
  db:
    image: mysql
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: project
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
    ports:
      - "9906:3306"
  client:
    build: ./client
    depends_on:
      - api
    ports:
      - 8080
    volumes:
      - ./client:/mnt/debug:rw
  security:
    build: ./security
    depends_on:
      - client
    ports:
      - 443:443
