version: '4.8.1'
services:
  db:
    image: mysql
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: project
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
    ports:
      - "9906:3306"
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 80:8000
    volumes:
      - ./api:/mnt/debug:ro
  client:
    build: ./client
    depends_on:
      - api
    ports:
      - 8080:8080
    volumes:
      - ./client:/mnt/debug:rw